# -*- mode: ruby -*-
# vi: set ft=ruby :

vm_provider = ENV["VAGRANT_PROVIDER"] || "virtualbox"
vm_net_ipv4_address = ENV["VAGRANT_IPV4_ADDRESS"] || "192.168.50.4"

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.network "private_network", ip: vm_net_ipv4_address

  config.vm.provider vm_provider do |v|
    v.memory = 1024*Integer(ENV["VAGRANT_RAM_GB"] || 1)
    v.cpus = Integer(ENV["VAGRANT_CPU_CORES"] || 1)
  end

  config.vm.provision "shell" do |s|
    ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
    s.inline = <<-SHELL
      VAGRANT_AUTH_KEYS=/home/vagrant/.ssh/authorized_keys
      [ ! -e $VAGRANT_AUTH_KEYS ] && touch $VAGRANT_AUTH_KEYS
      echo #{ssh_pub_key} >> $VAGRANT_AUTH_KEYS

      sudo apt-get update
      sudo apt-get install python3 python3-pip python3-dev -y

      [[ -f "$(dirname $(which python3))/python" ]] || \
      # If there's no python installed on the default path, use python3
      ln -s -f $(which python3) $(dirname $(which python3))/python && \
      ln -s -f $(which python3) /usr/local/bin/python && \
      pip3 install -U pip && \
      command -v pip >/dev/null || \
      # Same fallback for pip. No pip on default path == use pip3
      ln -s -f $(which pip3) $(dirname $(which pip3))/pip
    SHELL
  end
end
