# -*- mode: ruby -*-
# vi: set ft=ruby :

vm_provider = ENV["VAGRANT_PROVIDER"] || "virtualbox"
vm_net_ipv4_address = ENV["VAGRANT_IPV4_ADDRESS"] || "192.168.50.4"

Vagrant.configure("2") do |config|
  # NOTE: Box generated with HashiCorp Packer using nixbox
  # Ref: https://github.com/nix-community/nixbox
  config.vm.box = "nixos/22.05"
  config.vm.network "private_network", ip: vm_net_ipv4_address

  config.vm.provider vm_provider do |v|
    v.memory = 1024*Integer(ENV["VAGRANT_RAM_GB"] || 1)
    v.cpus = Integer(ENV["VAGRANT_CPU_CORES"] || 1)
  end

  config.vm.provision "shell" do |s|
    s.inline = <<-SHELL
      sudo nix-channel --add https://nixos.org/channels/nixos-unstable
      sudo nix-channel --add https://nixos.org/channels/nixpkgs-unstable
      sudo nix-channel --update

      sudo nix-env -iA nixos.vim nixos.git
    SHELL
  end
end
