# -*- mode: ruby -*-
# vi: set ft=ruby :

vm_provider = ENV["VAGRANT_PROVIDER"] || "virtualbox"
vm_net_ipv4_address = ENV["VAGRANT_IPV4_ADDRESS"] || "192.168.50.4"

Vagrant.configure("2") do |config|
  config.vm.box = "freebsd/FreeBSD-12.0-CURRENT"
  config.vm.network "private_network", ip: vm_net_ipv4_address
  config.ssh.shell = "sh"

  config.vm.base_mac = "080027D14C66"
  config.vm.synced_folder ".", "/vagrant", type: "rsync"

  config.vm.provider vm_provider |v|
    v.memory = 1024*Integer(ENV["VAGRANT_RAM_GB"] || 4)
    v.cpus = Integer(ENV["VAGRANT_CPU_CORES"] || 2)

    v.customize ["modifyvm", :id, "--hwvirtex", "on"]
    v.customize ["modifyvm", :id, "--audio", "none"]
    v.customize ["modifyvm", :id, "--nictype1", "virtio"]
    v.customize ["modifyvm", :id, "--nictype2", "virtio"]
  end

  config.vm.provision :shell do |s|
    ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
    s.inline = <<-SHELL
      VAGRANT_AUTH_KEYS=/home/vagrant/.ssh/authorized_keys 
      [ ! -e $VAGRANT_AUTH_KEYS ] && touch $VAGRANT_AUTH_KEYS
      echo #{ssh_pub_key} >> $VAGRANT_AUTH_KEYS
      pkg install -y py27-pip gtar
      ln -s /usr/local/bin/python2.7 /usr/bin/python
    SHELL
  end
end
